[project]
name = "flaskr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "pytest>=8.4.2",
]
[tool.pytest.ini_options]
pythonpath = ["."]